Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.disksize.size = '100GB'
  config.vm.hostname = "debian-opensearch"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.56.161", name: "vboxnet0"
  config.vm.network "public_network", bridge: "wlan0"
  config.vm.provider "virtualbox" 
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 2
    vb.name = "Debian-OpenSearch"
  end
  config.vm.provision "shell", inline: <<-SHELL
    # Update /etc/hosts file
    echo -e "192.168.56.160 wazuh.indexer wazuh.manager wazuh.dashboard" >> /etc/hosts
    apt update && apt full-upgrade -y && apt autoremove -y 
    # Add Docker's official GPG key:
    apt-get update
    apt-get -y install ca-certificates curl
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

    # Add the repository to Apt sources:
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update && apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
    usermod -aG docker vagrant
    rm -rf /var/lib/apt/lists/*

    echo "vm.max_map_count=262144" >> /etc/sysctl.conf && sysctl -p
    # Install Wazuh Docker
    cd /vagrant && docker compose up -d 
    SHELL
end
