Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.disksize.size = '100GB'
  config.vm.hostname = "debian-wazuh-dashboard"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.56.102", name: "vboxnet0"
  config.vm.network "public_network", bridge: "wlan0"
  config.vm.provider "virtualbox" 
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "Debian-Wazuh-Dashboard"
  end
  config.vm.provision "shell", inline: <<-SHELL
    # Update /etc/hosts file
      echo -e "0.0.0.0 debian.wazuh.dashboard\n192.168.56.100 debian.wazuh.indexer\n192.168.56.101 debian.wazuh.server" >> /etc/hosts
      apt update && apt full-upgrade -y && apt autoremove -y
      #
      apt-get -y install debconf adduser procps debhelper tar libcap2-bin gnupg apt-transport-https curl wget lsb-release
      # Install Wazuh Indexer
      curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
      echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
      apt-get update && apt-get -y install wazuh-dashboard
      cp -r /vagrant/wazuh-certificates/ /etc/wazuh-dashboard/
      chmod 500 /etc/wazuh-dashboard/ && chmod 400 /etc/wazuh-dashboard/wazuh-certificates/* && chown -R wazuh-dashboard:wazuh-dashboard /etc/wazuh-dashboard/wazuh-certificates/
      cp /vagrant/opensearch_dashboards.yml /etc/wazuh-dashboard/opensearch_dashboards.yml
      chmod 640 /etc/wazuh-dashboard/opensearch_dashboards.yml && chown wazuh-dashboard:wazuh-dashboard /etc/wazuh-dashboard/opensearch_dashboards.yml 
      systemctl daemon-reload && systemctl enable wazuh-dashboard && systemctl start wazuh-dashboard  
      # cp /vagrant/wazuh.yml /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml 
      # chmod 600 /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml && chown wazuh-dashboard:wazuh-dashboard /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
      SHELL
end
