Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.disksize.size = '100GB'
  config.vm.hostname = "debian-wazuh-docker"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.56.160", name: "vboxnet0"
  config.vm.network "public_network", bridge: "wlan0"
  config.vm.provider "virtualbox" 
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 8
    vb.name = "Debian-Wazuh-Docker"
  end
  config.vm.provision "shell", inline: <<-SHELL
    # Update /etc/hosts file
    echo -e "0.0.0.0 wazuh.indexer wazuh.manager wazuh.dashboard" >> /etc/hosts
    apt update && apt full-upgrade -y && apt autoremove -y 
    # Add Docker's official GPG key:
    apt-get update
    apt-get -y install ca-certificates curl
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

    # Add the repository to Apt sources:
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update && apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
    usermod -aG docker vagrant
    rm -rf /var/lib/apt/lists/*
    sysctl -w vm.max_map_count=262144
    echo "vm.max_map_count=262144" >> /etc/sysctl.conf
    # Install Wazuh Docker
    git clone https://github.com/wazuh/wazuh-docker.git -b v4.12.0
    cd /home/vagrant/wazuh-docker/single-node && \
    # Generate certificates for Wazuh Indexer
    docker compose -f generate-indexer-certs.yml run --rm generator && \
    docker compose up -d 
    SHELL
end
